title:  Nitish Aggarwal

# Change 'comments' to true for Disqus comments
# disqus:
#   comments: false
#   disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: 'UA-112060364-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/Nitish145'}
- {icon: 'twitter', link: 'https://twitter.com/NitishA27612143'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/nitish-aggarwal-105739175/'}
- {icon: 'envelope', link: 'mailto:naggarwal@me.iitr.ac.in'}
- {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
